# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches: 
      - 'develop'
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.8'

    - name: Get Swift version
      run: swift --version

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
